
import { Roboto_Serif } from "next/font/google";
import "./globals.css";

const roboto = Roboto_Serif({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"]
})
function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} font-sans max-w-screen-maxW m-auto box-border bg-[#F7F7F7]`}>
        {children}
      </body>
    </html>
  );
}